---
- hosts: $hosts
  user: $user
  sudo: yes
  sudo_user: root

  vars_files:
    - vars/elasticsearch.yml

  tasks:
    - include: tasks/setup.yml

  handlers:
    - include: handlers/elasticsearch.yml
