---
# Install Elasticsearch dependencies
- name: "Install Elasticsearch dependencies"
  apt: pkg=${item} state=installed update-cache=yes
  with_items: ${elasticsearch.dependencies}
  tags:
    - elasticsearch

# Fetch Elasticsearch Debian package
- name: "Fetch Elasticsearch: ${elasticsearch.url}/${elasticsearch.debian_package}"
  get_url: url=${elasticsearch.url}/${elasticsearch.debian_package} dest=${tmp_dir} thirsty=yes mode=0440
  register: elasticsearch_deb
  tags:
    - elasticsearch

# Install Elasticsearch
- name: "Install Elasticsearch package: ${elasticsearch.debian_package}"
  shell: "dpkg -i -E ${tmp_dir}/${elasticsearch.debian_package} 2>&1 | grep skipping | wc -l"
  when_changed: ${elasticsearch_deb}
  tags:
    - elasticsearch

# Add JAVA_HOME var in init script
- name: "Add JAVA_HOME to Elasticsearch init script"
  lineinfile: dest=/etc/init.d/${elasticsearch.service} state=present regexp="^JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64" insertafter="^DEFAULT=/etc/default/" line="JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64"
  notify:
    - "Restart Elasticsearch"
  tags:
    - elasticsearch

# Change Elasticsearch bind IP
- name: "Change Elasticsearch bind IP: ${elasticsearch.config}"
  lineinfile: "dest=${elasticsearch.config} state=present regexp='^network.host' insertafter='# network.host' line='network.host: ${with_elasticsearch_ip}'"
  notify:
    - "Restart Elasticsearch"
  tags:
    - elasticsearch

# Ensure Elasticsearch is running
- name: "Ensure Elasticsearch is running"
  service: name=${elasticsearch.service} state=started
  tags:
    - elasticsearch