---
# Add apt key for repo
- name: 'Adding apt key for elasticsearch repo'
  apt_key: url="{{ elasticsearch.key }}" state=present
  tags:
    - logstash
    - logstash-repository

# Add ES Elasticsearch repo 
- name: 'Adding ES repostory to sources.list.d'
  apt_repository: repo="{{ elasticsearch.repo}}" state=present
  tags:
    - logstash
    - logstash-repository

# Install Elasticsearch
- name: "Installing elasticsearch"
  apt: pkg=elasticsearch update_cache=yes

# Ensure Elasticsearch is running
- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.service }} state=started